2022-01-17 19:42:04,446 INFO    MainThread:10126 [wandb_setup.py:_flush():71] setting env: {}
2022-01-17 19:42:04,446 INFO    MainThread:10126 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-17 19:42:04,446 INFO    MainThread:10126 [wandb_init.py:_log_setup():371] Logging user logs to /Users/pierreadda/Documents/Jedha_projects/footprophet/Padda/experimentation/wandb/run-20220117_194204-3fqck8vm/logs/debug.log
2022-01-17 19:42:04,446 INFO    MainThread:10126 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/pierreadda/Documents/Jedha_projects/footprophet/Padda/experimentation/wandb/run-20220117_194204-3fqck8vm/logs/debug-internal.log
2022-01-17 19:42:04,447 INFO    MainThread:10126 [wandb_init.py:init():404] calling init triggers
2022-01-17 19:42:04,447 INFO    MainThread:10126 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-17 19:42:04,447 INFO    MainThread:10126 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 1pnxgat9
2022-01-17 19:42:04,449 INFO    MainThread:10126 [wandb_run.py:finish():1457] finishing run padda/my-test-project/1pnxgat9
2022-01-17 19:42:04,528 INFO    MainThread:10126 [jupyter.py:save_history():429] not saving jupyter history
2022-01-17 19:42:04,528 INFO    MainThread:10126 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-17 19:42:04,528 INFO    MainThread:10126 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-17 19:42:04,529 INFO    MainThread:10126 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-17 19:42:04,529 INFO    MainThread:10126 [wandb_run.py:_restore():1752] restore
2022-01-17 19:42:04,708 INFO    MainThread:10126 [wandb_run.py:_restore():1752] restore
2022-01-17 19:42:04,722 ERROR   MainThread:10126 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1963, in _on_finish
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_telemetry
    self._publish(rec)
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 45, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/pierreadda/opt/anaconda3/envs/foot_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-01-17 19:42:14,221 INFO    MainThread:10126 [wandb_setup.py:_flush():71] setting env: {}
2022-01-17 19:42:14,221 INFO    MainThread:10126 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-17 19:42:14,222 INFO    MainThread:10126 [wandb_init.py:_log_setup():371] Logging user logs to /Users/pierreadda/Documents/Jedha_projects/footprophet/Padda/experimentation/wandb/run-20220117_194214-277bafv6/logs/debug.log
2022-01-17 19:42:14,222 INFO    MainThread:10126 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/pierreadda/Documents/Jedha_projects/footprophet/Padda/experimentation/wandb/run-20220117_194214-277bafv6/logs/debug-internal.log
2022-01-17 19:42:14,222 INFO    MainThread:10126 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x176528f10>
2022-01-17 19:42:14,222 INFO    MainThread:10126 [wandb_init.py:init():404] calling init triggers
2022-01-17 19:42:14,223 INFO    MainThread:10126 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-17 19:42:14,223 INFO    MainThread:10126 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 1pnxgat9
2022-01-17 19:42:14,224 INFO    MainThread:10126 [wandb_run.py:finish():1457] finishing run padda/my-test-project/1pnxgat9
2022-01-17 19:42:14,225 INFO    MainThread:10126 [jupyter.py:save_history():429] not saving jupyter history
2022-01-17 19:42:14,225 INFO    MainThread:10126 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-17 19:42:14,225 INFO    MainThread:10126 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-01-17 19:42:14,227 INFO    MainThread:10126 [wandb_init.py:init():460] starting backend
2022-01-17 19:42:14,227 INFO    MainThread:10126 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-01-17 19:42:14,231 INFO    MainThread:10126 [backend.py:ensure_launched():216] starting backend process...
2022-01-17 19:42:14,241 INFO    MainThread:10126 [backend.py:ensure_launched():221] started backend process with pid: 10747
2022-01-17 19:42:14,244 INFO    MainThread:10126 [wandb_init.py:init():469] backend started and connected
2022-01-17 19:42:14,288 INFO    MainThread:10126 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-17 19:42:14,288 INFO    MainThread:10126 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-17 19:42:14,288 INFO    MainThread:10126 [wandb_init.py:init():533] updated telemetry
2022-01-17 19:42:14,331 INFO    MainThread:10126 [wandb_init.py:init():563] communicating current version
2022-01-17 19:42:16,384 INFO    MainThread:10126 [wandb_init.py:init():568] got version response 
2022-01-17 19:42:16,385 INFO    MainThread:10126 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-17 19:42:16,695 INFO    MainThread:10126 [wandb_init.py:init():606] starting run threads in backend
2022-01-17 19:42:21,707 INFO    MainThread:10126 [wandb_run.py:_console_start():1810] atexit reg
2022-01-17 19:42:21,709 INFO    MainThread:10126 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-17 19:42:21,710 INFO    MainThread:10126 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-17 19:42:21,711 INFO    MainThread:10126 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-17 19:42:21,711 INFO    MainThread:10126 [wandb_init.py:init():633] run started, returning control to user process
